'use client';
import {useEffect,useState} from 'react';import {supabaseBrowser} from '@/lib/supabase/browser';
type Job={id:string;topic:string;status:string;progress:number;output_url?:string;youtube_video_id?:string};
export default function Home(){const [topic,setTopic]=useState('');const [jobs,setJobs]=useState<Job[]>([]);const [busy,setBusy]=useState(false);const [yt,setYt]=useState(false);const [brand,setBrand]=useState<any>(null);const [schedule,setSchedule]=useState('');
async function load(){const r=await fetch('/api/analytics');if(r.ok){const x=await r.json();setJobs(x.recentJobs||[])}const y=await fetch('/api/youtube/status');if(y.ok)setYt((await y.json()).connected);const b=await fetch('/api/brand');if(b.ok)setBrand(await b.json())}useEffect(()=>{load();const t=setInterval(load,5000);return()=>clearInterval(t)},[]);
async function generate(){if(!topic.trim())return;setBusy(true);await fetch('/api/jobs',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({topic})});setTopic('');setBusy(false);load()}
async function publish(id:string){await fetch(`/api/jobs/${id}/publish`,{method:'POST'});load()}
async function logout(){await fetch('/api/auth/logout',{method:'POST'});location.href='/auth/login'}
return <main className="shell"><header><div><b>{brand?.name||'Hero AI Shorts Factory'}</b><span>Production Shorts Studio</span></div><nav><a href="/api/youtube/auth">{yt?'YouTube connected':'Connect YouTube'}</a><button onClick={logout}>Sign out</button></nav></header><section className="hero"><h1>Turn one idea into a publish-ready Short.</h1><p>AI script → voice → visuals → Remotion → MP4 → YouTube.</p><div className="composer"><textarea value={topic} onChange={e=>setTopic(e.target.value)} placeholder="e.g. 5 AI automations every small business should use"/><button onClick={generate} disabled={busy}>{busy?'Queueing…':'Generate Short'}</button></div></section><section className="grid"><div className="panel"><h2>Recent jobs</h2>{jobs.length===0?<p>No jobs yet.</p>:jobs.map(j=><article key={j.id} className="job"><div><strong>{j.topic}</strong><small>{j.status} · {j.progress}%</small></div><div>{j.output_url&&<><video src={j.output_url} controls playsInline/><a href={j.output_url} download>Download MP4</a>{yt&&<button onClick={()=>publish(j.id)}>Publish</button>}</>}</div></article>)}</div><div className="panel"><h2>Automation</h2><p>Daily generation is driven by Supabase schedules and the cron endpoint.</p><input value={schedule} onChange={e=>setSchedule(e.target.value)} placeholder="Daily topic template"/><button onClick={async()=>{await fetch('/api/schedules',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:'Daily Shorts',topic_template:schedule,cron:'0 8 * * *',timezone:'Africa/Kigali',auto_publish:false})});setSchedule('')}}>Create daily schedule</button><p className="muted">Configure Vercel Cron to call <code>/api/cron/schedules</code> with CRON_SECRET.</p></div></section></main>}
